### ISSUE TITLE
Research how to use css

### ISSUE THREAD

**Issue by 2ECC71** [pvtworld/pvt#10]
How should we use css?
We need a solution that supports different screen sizes and browsers. 

There are some [limitations](https://github.com/facebookincubator/create-react-app#limitations) if we want to avoid ejecting from create-react-app.
 
Perhaps [Bootstrap](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-bootstrap) could be a good idea?

Is there another framework we can use that integrates well with react?

**Comment by 2ECC71** [comment]
[react-bootstrap](https://react-bootstrap.github.io/introduction.html) does look like a nice simple solution. But perhaps we should list some requirements?

**Comment by nij0** [comment]
[Foundation](https://react.foundation/) does also look neat. One of the react courses cover most of it.

**Comment by nij0** [comment]
Both bootstrap and foundation seems to be responsive i.e. will work on whatever device user is using. Bootstrap is the most popular out of the two and will probably suit our needs perfectly.

**Comment by 2ECC71** [comment]
Great! Let's use Bootstrap,I've had succes suing it before.

**Comment by nij0** [comment]
At the moment we're using both standard css and Bootstrap. Bootstrap is very useful for buttons, navbars, forms etc, but when it comes to aligning stuff I find it pretty hard to use. However, the decision is still Bootstrap as it seems to be the best compared to many other frameworks.
