### ISSUE TITLE
Research map solution

### ISSUE THREAD

**Issue by 2ECC71** [pvtworld/pvt#11]
We need a map solution for the app.

What alternatives are there?
What features do we need?

**Comment by nij0** [comment]
Find users location:
https://github.com/colynb/react-geo-location
Google maps:
Insert and delete pins in map etc
https://github.com/tomchentw/react-google-maps

**Comment by nij0** [comment]
How to create a Map component:
https://www.fullstackreact.com/articles/how-to-write-a-google-maps-react-component/#

**Comment by nij0** [comment]
An article that I found interesting. "Firebase is a Database as a Service which lets you store and synchronize data in (near) real-time." - Maybe we can make use of that?
https://moquet.net/blog/realtime-geolocation-tracking-firebase/

**Comment by 2ECC71** [comment]
The copper coordinates are in a format called EPSG:3011 SWEREF99 18 00
We need a way to convert them to Google Map compatible coordinates in the EPSG:4326 WGS 84 system.

This can be done by hand here: https://epsg.io/transform#s_srs=3011&t_srs=4326&x=153727.5061408&y=6579025.7867566

And using a js library: http://proj4js.org/
This is the projection settings for 3011: `+proj=tmerc +lat_0=0 +lon_0=18 +k=1 +x_0=150000 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs `

**Comment by 2ECC71** [comment]
Have implemented a simple map with polygon drawing using react-google-maps

**Comment by 2ECC71** [comment]
I think react-google-maps makes a lot of sense. Im gonna close this issue.
