### ISSUE TITLE
Research/Create social media login

### ISSUE THREAD

**Issue by 2ECC71** [pvtworld/pvt#12]
**The user should be able to login using Google, Facebook or Github.**

### User story:
As a user I want to use my existing social media accounts to login.

### Definition of done:

- [x] Landing page displays a login button/overlay
- [x] Google Login
- [x] Facebook Login
- [x] Github Login
- [x] User is greeted with her/his name after login

**Comment by 2ECC71** [comment]
perhaps [firebase](https://firebase.google.com/) for auth as well?

**Comment by nij0** [comment]
"User is greeted with her/his name after login" will be implemented in a different component, kinda like Dashboard.js later on.
