### ISSUE TITLE
Create helper for conversion of coordinates from GoogleMap to SthlmApi

### ISSUE THREAD

**Issue by 2ECC71** [pvtworld/pvt#18]
We need to parse the polygons from the koppartaks api and convert the polygon coordinated contained in the `<geom>` tag to the projection system used by google maps.

Create a React Component that querys the kopparkas api for all roofs in the users vicinity and saves them in the correct format in the user state, accessible for the map component.

We need some kind of XML parser, options?

Details for projection conversions are in #11

**Comment by tahnhem** [comment]
How to use the intersect-function of the Koppartak-api.
http://miljodata.stockholm.se/api/koppartak-1997-ytor?Geom=POINT%20(154123.0%206579104.0000001)callback=?

**Comment by tahnhem** [comment]
proj4js is probably a better solution since epsg.io truncates the result to 2 decimals when converting from EPSG:4326 (google maps) to EPSG:3011 (koppartaks api). The other way around works fine though.

**Comment by nij0** [comment]
Great job!
I tested in and came to a conclusion that it works once I hit Adolf Fredriks Kyrka. http://www.kyrktorget.se/files/e8ea25c4dff0cf62382ca0acd7d0a452.png very much copper

**Comment by nij0** [comment]
Shouldn't this issue get closed?

**Comment by nij0** [comment]
Closing because is fixed in [#64](https://github.com/pvtworld/pvt/pull/64)
