### ISSUE TITLE
implement react-router 4h

### ISSUE THREAD

**Issue by nij0** [pvtworld/pvt#20]
User should be able to navigate between different pages/components. We need to decide what components are really needed. Then we're able to expand this issue requirement. 

For now: 
- First component to render is a login component
- After login user will be directed to CopperMap component

We're going to use the 2.8.1 version, but there's a forth out and might be better. We can probably migrate to that version later if the second doesn't suit our needs.

EDIT:
react-router version 4 will be used.

EDIT 2:

react-router got removed because it doesn't like passing state.

**Comment by 2ECC71** [comment]
Super @nij0 !
There are some issues with client side routing (React router) when deploying to github pages, see: [Gh pages section in create-react-app readme](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#notes-on-client-side-routing)

**Comment by loxtank** [comment]
react-router uses [semantic versioning](http://semver.org/) so there might be major breaking api changes between versions. What's the reason to go with v2 instead of v4?

**Comment by nij0** [comment]
We need to keep authorization in mind when using routing. There's plenty of docs on how to do this with Firebase auth

**Comment by nij0** [comment]
Closed due to problems with firebase sync. We're currently using a different routing solution.
