### ISSUE TITLE
Redesign components

### ISSUE THREAD

**Issue by nij0** [pvtworld/pvt#204]
- [x] Profil

Designen skall förändras, bl.a rubrik.

Ta bort Logged in as

Ta bort uid

Ompositionerna bild

koppla Num roofs stolen till stolenRoofs 

Lägg till enhet på area

- [x] Leaderboard

Göra current rank synligare

Göra leaderboard till lista istället

- [x] Stolen

 roofs

Value istället för Points

Ok/Cancel dialog when roof removed

- [x] Game stats

Redesigna klockan. Ta bort timmar, minuter, sekunder

- [x] Chat (Niclas)

Make visible on all devices

- [x] UserScore (Niclas)

Svart bakgrund för poängen

**Comment by nij0** [comment]
I'll fix Chat and UserScore

**Comment by LudvigLundberg** [comment]
Stolen Roofs, done!
