### ISSUE TITLE
Center the map around the user

### ISSUE THREAD

**Issue by LudvigLundberg** [pvtworld/pvt#29]
The map should not be moveable and be centered around the user.

**Comment by 2ECC71** [comment]
This can easily be implemented by adding:
`draggable: false,
            scrollwheel: false,
            panControl: false,
            maxZoom: 18,
            minZoom: 18,
            zoom: 18,`
to the `options` object in the <GoogleMap> component.
However, this is super annoying during development, so I'll close this and we'll implement it in release versions.
