### ISSUE TITLE
Change hosting to firebase

### ISSUE THREAD

**Issue by 2ECC71** [pvtworld/pvt#34]
After listening to a couple of podcast on firebase I believe we should host our app on firebase instead of github pages. I think the router configuration will be easier on firebase, there is an option to route all requests to index.html.

**Comment by nij0** [comment]
Awesome!

**Comment by 2ECC71** [comment]
We are now live @ https://coppercrown-a18fd.firebaseapp.com/

**Comment by 2ECC71** [comment]
ATM I believe I'm the only one authorized to deploy. I'll look into how to give you access to the site @ firebase

edit: Send me your firebase login email and I'll add you to the owner/editor IAM

**Comment by 2ECC71** [comment]
PR #35 fixes this
