### ISSUE TITLE
Research on modeling/visual representation

### ISSUE THREAD

**Issue by tiliacordata** [pvtworld/pvt#39]
What is the best way to visually represent the structure and flow of information in our app to create a common understanding of it in our team? Which information do we need to capture, what kind of diagrams could we use?

Maybe we can draw some inspiration from here: http://zf4.biz/blog

I tried out PlantUML, a textbased way of representing UML diagrams: http://www.plantuml.com I like it, it seems to make it easy to save and update diagrams.

**Comment by tiliacordata** [comment]
An example of a class diagram is available in Drive.

**Comment by nij0** [comment]
Superb! The class diagram in Drive is very explaining and easy to understand, great job!
