### ISSUE TITLE
Safari NOT compatible

### ISSUE THREAD

**Issue by Murmellow** [pvtworld/pvt#82]
When using Safari to log out I cannot log in, regardless of github/facebook/google. However it does work with chrome.

**Comment by 2ECC71** [comment]
I cant reproduce this. Please try with the latest deployed build on coppercrown.space
Also, use a inkognito window to prevent cache

**Comment by Murmellow** [comment]
During attempt to reproduce it seems to work, might be a problem related to cache and multiple browsers running. Closed due to currently working and not reproduced, although this occurred five attempts then suddenly worked.
