### ISSUE TITLE
Get the display name of user via login provider for certain components to display

### ISSUE THREAD

**Issue by nij0** [pvtworld/pvt#86]
This can be achieved with "user.displayName".

**Comment by Murmellow** [comment]
Need help with how firebase work in conjunction with this. 

See the navbar title calling a titleName() with returns a string of "Signed in: " and the displayName.

View feature-displayName branch latest commit. Note: Non-compiling / Bugged branch (View Navigationbar.jsx)

**Comment by Murmellow** [comment]
Issue resolved.
